version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:8000"
    restart: always

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    ports:
      - "3308:3306"
