# Generated by Django 4.1 on 2022-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
